version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/database.sqlite:/usr/src/app/database.sqlite
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server
